### ISSUE TITLE
GenealogyInPopTree.c&.h are obsolete

### ISSUE THREAD

**Issue by selotape** [gphocs-dev/G-PhoCS#15]
GenealogyInPopTree is an obsolete file developed by Ilan long long ago

**Comment by gphocs-dev** [comment]
I'm assigning this to @evgenyidc when he gets back to work. Files that need to be removed from all repositories:
- LocusGenealogy.c
- LocusGenealogy.h
- GenealogyInPopTree.c
- GenealogyInPopTree.h

**Comment by evgenyidc** [comment]
Removing files from "dev" branch. 
Plan: to remove them from "master" by pull request upon release of version 1.3.1.
