### ISSUE TITLE
GPhoCS.h and patch.h

### ISSUE THREAD

**Issue by gphocs-dev** [gphocs-dev/G-PhoCS#18]
These new header files seem fine, but global variables should be migrated out of them and into the appropriate C file. The header files should contain only function / variable declarations and type definition. Global variable declaration is done via the extern command.

**Comment by selotape** [comment]
Evgeny, may I leave this to you (moving the globals into C files)?

**Comment by gphocs-dev** [comment]
This is fine for now. Seems like the only problem this can cause is prompting an "unused variable" warning if a C file includes the h files but doesn't access one of the variables there. We'll look into this later (not urgent).
