### ISSUE TITLE
misspelling in MCMCControl.h

### ISSUE THREAD

**Issue by selotape** [gphocs-dev/G-PhoCS#24]
Hi,

There's a small misspelling in MCMCControl.h. 
It says `UPDATE_STAST` instead of `UPDATE_STATS`.
see line - [https://github.com/gphocs-dev/G-PhoCS/blob/master/src/MCMCcontrol.h#L25](https://github.com/gphocs-dev/G-PhoCS/blob/master/src/MCMCcontrol.h#L25)

**Comment by evgenyidc** [comment]
Fix will be submitted with the next commit
