### ISSUE TITLE
Bad usage of processHetPatterns()

### ISSUE THREAD

**Issue by selotape** [gphocs-dev/G-PhoCS#28]
My IDE noticed a misusage of a function in `AlignmentProcessor.cpp` - 

[(https://github.com/gphocs-dev/G-PhoCS/blob/master/src/AlignmentMain.c#L118](https://github.com/gphocs-dev/G-PhoCS/blob/master/src/AlignmentMain.c#L118)

Here we give the function `processHetPatterns()` only one parameter though it requires seven.

I've no idea why this is or whether it causes any real issue.

**Comment by gphocs-dev** [comment]
Okay. Evgeny looked at this. AlignmentMain.c contains several faulty calls
to functions in AlignmentProcessor.cpp. This is probably rooted in
"ancient" modifications of the code. For now, we flagged this source file
as "buggy" and removed its compilation from the Makefile.

--Ilan

**Comment by evgenyidc** [comment]
Fix of Makefile will be provided with the next commit.
