### ISSUE TITLE
Segmentation Fault (Core Dumped) after MCMC finishes

### ISSUE THREAD

**Issue by g33k5p34k** [gphocs-dev/G-PhoCS#52]
Hi there, 

G-PhoCS has been crashing for me just after the MCMC run finishes, even after reducing the number of individuals from 33 (for 2966 loci) to 12 (4553 loci). I've tried running the 33-individual dataset in CIPRES and that one segfaults before the burn-in even finishes. 
[batch_1_gphocs_33_indiv.ctrl.txt](https://github.com/gphocs-dev/G-PhoCS/files/2831228/batch_1_gphocs_33_indiv.ctrl.txt)
[batch_1_gphocs_33_indiv.out.gz](https://github.com/gphocs-dev/G-PhoCS/files/2831229/batch_1_gphocs_33_indiv.out.gz)
[batch_1_gphocs_12_indiv.ctrl.txt](https://github.com/gphocs-dev/G-PhoCS/files/2831240/batch_1_gphocs_12_indiv.ctrl.txt)
[batch_1_gphocs_12_indiv.out.gz](https://github.com/gphocs-dev/G-PhoCS/files/2831241/batch_1_gphocs_12_indiv.out.gz)

**Comment by gphocs-dev** [comment]
Did you end up fixing this? Sorry I didn't have time to look into this.

**Comment by focusjava** [comment]
./bin/G-PhoCS sample-control-file.ctl -n 8
**************************************************************

G-Phocs version 1.3.2,  Oct. 2017

**************************************************************
Setting Thread Count to: 8
Reading control settings from file sample-control-file.ctl...
Done.
Reading sequence data...  1000 loci, as specified in sequence file seqs-sample.txt.
Reading loci (.=100 loci): .......... 

Starting MCMC: 0 burnin, 5000 running, sampled every 0 iteration(s).
There are 11 parameters in the model.
Samples   CoalTimes MigTimes  SPRs      Thetas    MigRates TAU_ 4    TAU_ 5    TAU_ 6    RbberBnd  MutRates  Mixing    | DATA-ln-ld |  TIME
-----------------------------------------------------------------------------------------------------------------------------------------------------
    500    64.5%     99.3%     71.5%     64.4%     95.8%     41.5%     30.7%     81.8%       0.0%       1000    63.4%     99.9%     72.4%     72.9%     96.2%     44.3%     32.3%     85.4%       0.0%       1500    63.1%     99.8%     72.2%     73.3%     95.4%     14.8%     12.0%     98.6%       0.0%       2000    63.0%     99.8%     72.2%     72.7%     98.6%     34.3%     20.4%     88.6%       0.0%       2500    63.0%    100.0%     72.5%     73.6%     96.8%     27.9%     27.9%     93.8%       0.0%       3000    63.6%     99.9%     71.1%     73.1%     97.0%     15.6%     14.0%     93.4%       0.0%       3500    63.1%    100.0%     72.0%     74.7%     97.8%     37.9%     32.7%     83.8%       0.0%       4000    62.7%    100.0%     72.9%     73.1%     96.8%      5.2%      3.2%     91.4%       0.0%       4500    63.4%     99.9%     72.8%     74.8%     95.8%     10.4%      7.6%     90.2%       0.0%       5000    62.2%    100.0%     73.1%     73.6%     95.4%     23.2%     19.6%    102.6%       0.0%      0.0%     88.8%    |-1348.996398|  1:24

MCMC finished. Time used:  1:24
Segmentation fault

echo |cpp -fopenmp -dM | grep -i openmp
#define _OPENMP 201107

What's wrong with this mistake？？？
