### ISSUE TITLE
Can't load trace files

### ISSUE THREAD

**Issue by btmartin721** [gphocs-dev/G-PhoCS#63]
Hello, 

I am trying to load my trace files into Tracer and readTrace, and neither will work. I have attached one of my trace files.

If I try to run readTrace, I get the following error:

```Unable to count lines of the trace file```  

When I try to import it into Tracer, the program acts like it loads it but nothing happens. Nothing gets loaded.

Do you know what could be wrong? This is from a file that has not finished running yet, but I am trying to view the traces while it's still running (though the file is a copy, not the one being written to).

-Bradley

[box_gphocs_r1.log](https://github.com/gphocs-dev/G-PhoCS/files/3833527/box_gphocs_r1.log)

**Comment by gphocs-dev** [comment]
Dear Martin,

The trace file looks completely fine to me. I was able to open it without a problem using Tracer v1.5. I know from other user posts that the latest version of Tracer sometimes does not work. We'll have to look into that to see what's causing this. I also notice now that there is a minor bug in our readTrace program that prevents it from correctly reading trace files. We'll add this to our bug list and fix it soon.

Sorry for the inconvenience.

--Ilan

**Comment by btmartin721** [comment]
Thank you for your help. I'll give an older version of Tracer a try. If I don't have success I'll let you know. 

Also, I might have figured something out with the readTrace. Apparently G-Phocs puts an \r\n as the carriage return, whereas it should just be the Linux newline \n. I was using the latest dev version of G-Phocs (1.3).

So I removed the \r and it ran through readTrace. Not sure if it added the \r because of something I did or if it was just part of the code. I was running it on a Linux cluster (running CentOS 6).

-Bradley

**Comment by btmartin721** [comment]
Yes, Tracer v1.6 worked. Thanks again for your help.

-Bradley

**Comment by gphocs-dev** [comment]
As far as I can tell, the code is not explicitly writing \r characters into the trace files, so that is a bit odd. We'll have a look to see if there is some odd conversion issue involved. Anyway, I'm glad to see that it works out for you.
