### ISSUE TITLE
Two Issues: Multithreading and Finetuning

### ISSUE THREAD

**Issue by btmartin721** [gphocs-dev/G-PhoCS#66]
Hello,

I have come across two issues while trying to use G-Phocs 1.3.2.

First, multithreading. I have compiled the multithreading version, and made sure to delete the "#" in the makefile prior to doing so. During compilation, it says "compiling multithreaded version" (or something like that). However, when I run G-Phocs, the logfile says: "Setting Thread Count to: 1" even though I specified -n 16 when running G-Phocs.

My second question is with finetuning. I did the autotune with the first 10,000 iterations being used for the finetuning. However, I want to delay the start of the migration bands by 10,000. Will the mig-bands still undergo the finetuning procedure if they don't start being calculated until 10K iterations?

Thanks for your time.

-Bradley

**Comment by btmartin721** [comment]
Hello,

Quick update. For the finetuning, I just ran a preliminary run to determine good parameters. So my finetuning question is resolved.

However, I still can't get it to use multithreading. Here's the command I used to call G-Phocs:

```
$HOME/local/src/gphocs/G-PhoCS/bin/G-PhoCS gphocs.ctl -n 16 > $logfile 2>&1
```
Do you happen to know why multithreading doesn't seem to change the number of threads from 1?

Thanks,

-Bradley

**Comment by gphocs-dev** [comment]
If the output log says that it set the number of threads to 1, this means you're running the multi-threaded version. So you compiled your code successfully. The only reason I can think for this is if your system does not have support for mutli-threaded applications.  You need to make sure that your system can support Open MP applications.

**Comment by btmartin721** [comment]
Hi,

I did try the commands you listed in the manual to see if Open MP is present on the system. Here is the command and output:

```
echo | cpp -fopenmp -dM | grep -i openmp
#define _OPENMP 201307
```

I am using CentOS 6.10 on an HPC cluster and am using gcc version 4.4.7 if that helps.

-Bradley

**Comment by gphocs-dev** [comment]
Then this really should work. Have you run multi-threaded jobs on this cluster before? The number of threads is set as the min between the number that you specify and max number allowed by your system. If you don't specify the number of threads with the -n flag, then the number should be set to the max number according to your system constraints. The fact that you get allocated one thread appears to suggest that the system does not allow you to allocate more than one thread. You can make sure of that by running G-PhoCS without a -n flag. If you still set one thread, then you should ask your HPC admin how to raise the number of threads allowed for each job.

**Comment by btmartin721** [comment]
I have indeed run many jobs on these this cluster and also these nodes before. The nodes I am using have 16 cores with 32 threads, and I have run many different multithreaded programs on them (e.g., RAxML, IQ-TREE, and many others). So I don't think it's an issue with the node not being multithreading capable. I also tried using G-PhoCS without the -n flag and it still used 1 thread.

That being said, is it possible that my cluster has an old version of Open MP? This HPC cluster doesn't get updated often because it is running all the time and would break many software if they did that. E.g., it is running on CentOS 6.

I might try using newer versions of gcc. They have multiple gcc versions available as modules, and I have noticed that changing gcc also changes OpenMP versions. I will let you know if I have success, but if this isn't the problem, is there anything else you can think of that might be part of the problem?

Thanks very much for your time. It is greatly appreciated.

-Bradley

**Comment by btmartin721** [comment]
So changing the gcc and openmpi modules didn't seem to make it work. Still only uses one thread. Anyways, I'm out of ideas there. Not sure why it isn't working. I definitely have it set where it's allowed to use the full node (16 cores X 2 threads/core).

-Bradley

**Comment by gphocs-dev** [comment]
I wouldn't think that a newer version of gcc would help, but the version of OpenMP can possibly make a difference. I find this surprising since we developed this code a few years ago, and it uses pretty standard features of OpenMP. If you're able to pinpoint the problem, do post your solution here for others to learn from.

**Comment by yuntwang** [comment]
@gphocs-dev 

I ran into the same problem, is there a solution?

like this：

./bin/G-PhoCS sample-control-file.ctl -n 10
**************************************************************

G-Phocs version 1.3.2,  Oct. 2017

**************************************************************
Setting Thread Count to: 1
Reading control settings from file sample-control-file.ctl...
Done.
Reading sequence data...  1000 loci, as specified in sequence file seqs-sample.txt.
Reading loci (.=100 loci): .......... 

Starting MCMC: 0 burnin, 5000 running, sampled every 0 iteration(s).
There are 12 parameters in the model.
Samples   CoalTimes MigTimes  SPRs      Thetas    MigRates TAU_ 1    TAU_ 4    TAU_ 5    TAU_ 6    RbberBnd  MutRates  Mixing    | DATA-ln-ld |  TIME

**Comment by gphocs-dev** [comment]
Not yet I'm afraid. I cannot recreate this locally, which makes it
difficult to track down and debug.

--Ilan

**Comment by glaudelrio** [comment]
should an older version of G-PhoCS allow for multithreading correctly? I have faced the same issue.
Which version do you recommend?
thank you!!!

**Comment by igronau** [comment]
The issue is not the version of G-PhoCS, but the configuration of the cluster. Since I could not recreate the problem on my machines, I couldn't really find a workaround for this. Before you give up - are you sure that multithreading is not being turned on when you run G-PhoCS?

**Comment by t-vane** [comment]
Hi,

I would like to revive this discussion as I am facing the same issue with the multithreaded version:
No matter what -n I specify G-PhoCS always runs with only one thread. Compilation did not throw any warnings or error messages. The node I would like to use has 40 cores X 2 threads/core. Like @btmartin721 , I am frequently running multithreaded programs without issues on this node and others. 

Has anyone found a solution/workaround yet?

EDIT: 
I talked to one of our server admins who pointed out the solution: The environment variable "OMP_NUM_THREADS" is hard set to 1 on our system. Adding the line "export OMP_NUM_THREADS=$NCORES" to my job script where $NCORES is the number of cores I would like to use fixed the issue.

Kind regards,
Tobi

**Comment by igronau** [comment]
Thanks for this tip. I sure hope it will help others and will keep this in mind if this issue is raised by others.
Good luck with your analysis!

--Ilan
