### ISSUE TITLE
possibility to restart a G-PhoCS analysis

### ISSUE THREAD

**Issue by killidude** [gphocs-dev/G-PhoCS#68]
This is a request. Even servers that I have access to are subject to frequent power failures, and so it would be really helpful if G-PhoCS could safe a checkpoint, and then use this checkpoint to restart analyses. This would also be very useful if one needed to run an analysis longer.
Thank you,
Tomas Hrbek

**Comment by igronau** [comment]
This is on our list of high priority features to implement. I currently don't have a programmer working on this project, but when we continue active development, we'll take care of that.

**Comment by killidude** [comment]
Thanks for the super fast answer.
