### ISSUE TITLE
master branch

### ISSUE THREAD

**Issue by gphocs-dev** [gphocs-dev/G-PhoCS#7]
@evgenyidc - I updated the manual in the master branch (didn't have up-to-date version that was in dev) and noticed that the master branch still contains the ODT file for the manual in the main directory, not just in the doc/ directory. I removed it in my local git repo and did push, but it doesn't change. Can you look into this?

**Comment by gphocs-dev** [comment]
@evgenyidc - any updates on this?

**Comment by evgenyidc** [comment]
Done
