### ISSUE TITLE
unable to read trace file

### ISSUE THREAD

**Issue by glaudelrio** [gphocs-dev/G-PhoCS#77]
Hello! I am facing problems to read the trace file both in readTrace and Tracer. 
Here is an example of a really short trace file that I generated as a test.
Any idea on what would be the issue?
Thank you!

[mcmc_prior1_test3.log](https://github.com/gphocs-dev/G-PhoCS/files/6417542/mcmc_prior1_test3.log)

**Comment by igronau** [comment]
Apparently readTrace does not work on all platforms, and we stopped maintaining the code a while back. Personally, to view and analyze traces, I use [Tracer V15](http://tree.bio.ed.ac.uk/software/tracer/) (later versions don't always work).

**Comment by glaudelrio** [comment]
Hello! Thank you so much! In fact, I found what the error was. The trace file is being generated with an extra blank column. Once you open the text and remove that column everything works well!
