### ISSUE TITLE
Human

### ISSUE THREAD

**Issue by kmanoharan01** [gphocs-dev/G-PhoCS#79]
Can we use G-Phocs for human genomes? If so, do we need the complete chromosomal sequences?

**Comment by igronau** [comment]
Sure. That was our first application of G-PhoCS, now [more than 10 years ago](https://www.nature.com/articles/ng.937). All you need is high quality individual-level sequence data from ~10,000 loci located far enough from genes and conserved sequences.

**Comment by kmanoharan01** [comment]
Hi,

Thank you for your reply,

Can I use intron regions?

**Comment by igronau** [comment]
as long as you're far enough from an exon you should be fine. In the supplement of our paper we explore the influence of distance from exons, so you could get an idea how far you wish to be. You can read the exact criteria we used in our paper, and there's even a file with coordinates [here](http://compgen.cshl.edu/GPhoCS/data.php). Note that we used an outdated coordinate system (HG18).

**Comment by kmanoharan01** [comment]
Thanks very much for your help.
